<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (C) 2010 The Android Open Source Project
     Licensed under the Apache License, Version 2.0 (the "License");
     you may not use this file except in compliance with the License.
     You may obtain a copy of the License at
          http://www.apache.org/licenses/LICENSE-2.0
     Unless required by applicable law or agreed to in writing, software
     distributed under the License is distributed on an "AS IS" BASIS,
     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     See the License for the specific language governing permissions and
     limitations under the License.
-->
<!DOCTYPE MediaSettings [
  <!ELEMENT MediaSettings (CamcorderProfiles,
                         EncoderOutputFileFormat+,
                         VideoEncoderCap+,
                         AudioEncoderCap+,
                         VideoDecoderCap,
                         AudioDecoderCap)>
  <!ELEMENT CamcorderProfiles (EncoderProfile+, ImageEncoding+, ImageDecoding, Camera)>
  <!ELEMENT EncoderProfile (Video, Audio)>
  <!ATTLIST EncoderProfile quality (timelapsehigh|timelapselow|qcif|high|low) #REQUIRED>
  <!ATTLIST EncoderProfile fileFormat (mp4|3gp) #REQUIRED>
  <!ATTLIST EncoderProfile duration (30|60) #REQUIRED>
  <!ELEMENT Video EMPTY>
  <!ATTLIST Video codec (h264|h263|m4v) #REQUIRED>
  <!ATTLIST Video bitRate CDATA #REQUIRED>
  <!ATTLIST Video width CDATA #REQUIRED>
  <!ATTLIST Video height CDATA #REQUIRED>
  <!ATTLIST Video frameRate CDATA #REQUIRED>
  <!ELEMENT Audio EMPTY>
  <!ATTLIST Audio codec (amrnb|amrwb|aac) #REQUIRED>
  <!ATTLIST Audio bitRate CDATA #REQUIRED>
  <!ATTLIST Audio sampleRate CDATA #REQUIRED>
  <!ATTLIST Audio channels (1|2) #REQUIRED>
  <!ELEMENT ImageEncoding EMPTY>
  <!ATTLIST ImageEncoding quality (90|80|70) #REQUIRED>
  <!ELEMENT ImageDecoding EMPTY>
  <!ATTLIST ImageDecoding memCap CDATA #REQUIRED>
  <!ELEMENT Camera EMPTY>
  <!ATTLIST Camera previewFrameRate CDATA #REQUIRED>
  <!ELEMENT EncoderOutputFileFormat EMPTY>
  <!ATTLIST EncoderOutputFileFormat name (mp4|3gp) #REQUIRED>
  <!ELEMENT VideoEncoderCap EMPTY>
  <!ATTLIST VideoEncoderCap name (h264|h263|m4v) #REQUIRED>
  <!ATTLIST VideoEncoderCap enabled (true|false) #REQUIRED>
  <!ATTLIST VideoEncoderCap minBitRate CDATA #REQUIRED>
  <!ATTLIST VideoEncoderCap maxBitRate CDATA #REQUIRED>
  <!ATTLIST VideoEncoderCap minFrameWidth CDATA #REQUIRED>
  <!ATTLIST VideoEncoderCap maxFrameWidth CDATA #REQUIRED>
  <!ATTLIST VideoEncoderCap minFrameHeight CDATA #REQUIRED>
  <!ATTLIST VideoEncoderCap maxFrameHeight CDATA #REQUIRED>
  <!ATTLIST VideoEncoderCap minFrameRate CDATA #REQUIRED>
  <!ATTLIST VideoEncoderCap maxFrameRate CDATA #REQUIRED>
  <!ELEMENT AudioEncoderCap EMPTY>
  <!ATTLIST AudioEncoderCap name (amrnb|amrwb|aac) #REQUIRED>
  <!ATTLIST AudioEncoderCap enabled (true|false) #REQUIRED>
  <!ATTLIST AudioEncoderCap minBitRate CDATA #REQUIRED>
  <!ATTLIST AudioEncoderCap maxBitRate CDATA #REQUIRED>
  <!ATTLIST AudioEncoderCap minSampleRate CDATA #REQUIRED>
  <!ATTLIST AudioEncoderCap maxSampleRate CDATA #REQUIRED>
  <!ATTLIST AudioEncoderCap minChannels (1) #REQUIRED>
  <!ATTLIST AudioEncoderCap maxChannels (1) #REQUIRED>
  <!ELEMENT VideoDecoderCap EMPTY>
  <!ATTLIST VideoDecoderCap name (wmv) #REQUIRED>
  <!ATTLIST VideoDecoderCap enabled (true|false) #REQUIRED>
  <!ELEMENT AudioDecoderCap EMPTY>
  <!ATTLIST AudioDecoderCap name (wma) #REQUIRED>
  <!ATTLIST AudioDecoderCap enabled (true|false) #REQUIRED>
]>

<MediaProfileInfo>
    <CamcorderProfiles cameraId="0">
        <EncoderProfile quality="high" fileFormat="mp4" duration="60">
            <Video codec = "h264"  bitRate="1572000" width="640" height="480"
                frameRate = "20"/>
            <Audio codec="aac" bitRate="62900" sampleRate="48000"
                channels ="1" />
        </EncoderProfile>
        <EncoderProfile quality="low" fileFormat="mp4" duration="30">
            <Video codec = "h264"  bitRate="192000" width="176" height="144"
                frameRate = "20"/>
            <Audio codec="amrnb" bitRate="62900" sampleRate="48000"
                channels ="1" />
        </EncoderProfile>
        <ImageEncoding quality="70"/>
        <ImageEncoding quality="80"/>
        <ImageEncoding quality="90"/>
    </CamcorderProfiles>
    <CamcorderProfiles cameraId="1">
        <EncoderProfile quality="high" fileFormat="3gp" duration="60">
            <Video codec = "h264"  bitRate="720000" width="320" height="240"
                frameRate = "20"/>
            <Audio codec="aac" bitRate="62900" sampleRate="48000"
                channels ="1" />
        </EncoderProfile>
        <EncoderProfile quality="low" fileFormat="3gp" duration="30">
            <Video codec = "h263"  bitRate="192000" width="176" height="144"
                frameRate = "20"/>
            <Audio codec="amrnb" bitRate="62900" sampleRate="48000"
                channels ="1" />
        </EncoderProfile>
        <ImageEncoding quality="70"/>
        <ImageEncoding quality="80"/>
        <ImageEncoding quality="90"/>
    </CamcorderProfiles>
    <VideoEncoderCap name="h263" enabled="true" minBitRate="64000"
        maxBitRate="3078000" minFrameWidth="176" maxFrameWidth="640"
        minFrameHeight="144" maxFrameHeight="480"
        minFrameRate="1" maxFrameRate="30"/>
    <VideoEncoderCap name="m4v" enabled="true" minBitRate="64000"
        maxBitRate="3078000" minFrameWidth="176" maxFrameWidth="640"
        minFrameHeight="144" maxFrameHeight="480"
        minFrameRate="1" maxFrameRate="30"/>
    <VideoEncoderCap name="h264" enabled="true" minBitRate="64000"
        maxBitRate="3078000" minFrameWidth="176" maxFrameWidth="640"
        minFrameHeight="144" maxFrameHeight="480"
        minFrameRate="1" maxFrameRate="30"/>
    <AudioEncoderCap name="amrnb" enabled="true" minBitRate="5525"
        maxBitRate="12200" minSampleRate="8000" maxSampleRate="8000"
        minChannels="1" maxChannels="1"/>
    <AudioEncoderCap name="aac" enabled="true" minBitRate="5525"
        maxBitRate="128000" minSampleRate="8000" maxSampleRate="48000"
        minChannels="1" maxChannels="1"/>
    <VideoDecoderCap name="wmv" enabled="true"/>
    <AudioDecoderCap name="wma" enabled="true"/>
    <EncoderOutputFileFormat name="3gp"/>
    <EncoderOutputFileFormat name="mp4"/>
</MediaProfileInfo>
